OnlineShop/Controllers/Cart1Controller.cs
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Dao;
using PagedList;
using System.Web.Script.Serialization;
using Model.EF;
using System.Configuration;
using Common;

namespace OnlineShop.Controllers
{
    public class Cart1Controller : Controller
    {
        private readonly static string CartCoockies = (string)Common.CommonConstants.CART_COOKIES;
        // GET: Cart1
        public ActionResult Index()
        {
            var list = new List<CartItem>();
            /*int pageSize = 5;
            int pageNumber = (page ?? 1);*/
            var cart = Request.Cookies[CartCoockies];
            if (cart != null)
            {
                var it = cart.Value.Split(',').ToList();

                for (int i = 0; i < it.Count(); i++)
                {
                    if (it[i] != "")
                    {
                        var a = it[i].Split('-').ToList();
                        var product = new ProductDao().ViewDetail(long.Parse(a[0]));
                        var item = new CartItem();
                        item.Product = product;
                        item.Quantity = int.Parse(a[1]);
                        list.Add(item);
                    }
                }
            }
            return View(list);
        }
        public JsonResult AddToCart(long productId, int quantity)
        {
            var cart = Request.Cookies[CartCoockies];
            if (cart != null)
            {
                var list = new List<CartItem>();
                var it = cart.Value.Split(',').ToList();

                for (int i = 0; i < it.Count(); i++)
                {
                    if (it[i] != "")
                    {
                        var a = it[i].Split('-').ToList();
                        var product = new ProductDao().ViewDetail(long.Parse(a[0]));
                        var item = new CartItem();
                        item.Product = product;
                        item.Quantity = int.Parse(a[1]);
                        list.Add(item);
                    }
                }
                if (list.Exists(x => x.Product.ID == productId))
                {
                    Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(-1);
                    Response.SetCookie(Response.Cookies[CartCoockies]);
                    foreach (var item in list)
                    {
                        if (item.Product.ID == productId)
                        {
                            item.Quantity += quantity;
                        }

                        Response.Cookies[CartCoockies].Value = Response.Cookies[CartCoockies].Value + "," + item.Product.ID + "-" + item.Quantity; 
                    }
                }
                else
                {
                    Response.Cookies[CartCoockies].Value = Request.Cookies[CartCoockies].Value + "," + productId + "-" + quantity;
                }
                Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(1);
                Response.SetCookie(Response.Cookies[CartCoockies]);
            }
            else
            {
                Response.Cookies[CartCoockies].Value = productId + "-" + quantity;
                Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(1);
                Response.SetCookie(Response.Cookies[CartCoockies]);
            }
            //return RedirectToAction("Index");
            return Json(new { status = true, message = "Thêm thành công!" });
        }

        
        public JsonResult Delete(long id)
        {
            var cart = Request.Cookies[CartCoockies];
            if (cart != null)
            {
                var it = cart.Value.Split(',');
                var list = new List<CartItem>();
                for (int i = 0; i < it.Count(); i++)
                {
                    if (it[i] != "")
                    {
                        var a = it[i].Split('-').ToList();//đối với mỗi sản phẩm ta sẽ cắt chuỗi tại "-" để lấy ra id và số lượng
                        var product = new ProductDao().ViewDetail(long.Parse(a[0]));
                        var item = new CartItem();
                        item.Product = product;
                        item.Quantity = int.Parse(a[1]);
                        list.Add(item);
                    }


                }
                Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(-1);
                Response.SetCookie(Response.Cookies[CartCoockies]);
                list.RemoveAll(x => x.Product.ID == id);
                foreach (var item in list)
                {
                    Response.Cookies[CartCoockies].Value = Response.Cookies[CartCoockies].Value + "," + item.Product.ID + "-" + item.Quantity;
                    Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(1);
                    Response.SetCookie(Response.Cookies[CartCoockies]);

                }
            }
            return Json(new { status = true, message = "Xóa thành công!" });
        }

        [HttpDelete]
        public JsonResult DeleteAll()
        {
            Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(-1);
            Response.SetCookie(Response.Cookies[CartCoockies]);
            return Json(new { status = true, message = "Xóa thành công!" });
        }

       
        public JsonResult UpdateCart(string contentJson)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(contentJson);
            var cart = Request.Cookies[CartCoockies];
            if (cart != null)
            {
                var it = cart.Value.Split(',');
                var list = new List<CartItem>();
                for (int i = 0; i < it.Count(); i++)
                {
                    if (it[i] != "")
                    {
                        var a = it[i].Split('-').ToList();
                        var product = new ProductDao().ViewDetail(long.Parse(a[0]));
                        var item = new CartItem();
                        item.Product = product;
                        item.Quantity = int.Parse(a[1]);
                        list.Add(item);
                    }


                }
                Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(-1);
                Response.SetCookie(Response.Cookies[CartCoockies]);
                foreach (var item in list)
                {
                    var jsonItem = jsonCart.SingleOrDefault(x => x.Product.ID == item.Product.ID);
                    if (jsonItem != null)
                    {
                        item.Quantity = jsonItem.Quantity;
                    }
                    Response.Cookies[CartCoockies].Value = Response.Cookies[CartCoockies].Value + "," + item.Product.ID + "-" + item.Quantity;
                    Response.Cookies[CartCoockies].Expires = DateTime.Now.AddYears(1);
                    Response.SetCookie(Response.Cookies[CartCoockies]);

                }
            }
            return Json(new { status = true, message = "Cập nhật thành công!" });
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var list = new List<CartItem>();
            var cart = Request.Cookies[CartCoockies];
            var user = Request.Cookies["username"];
            ViewBag.shipName = "";
            ViewBag.mobile = "";
            ViewBag.address = "";
            ViewBag.email = "";
            if (cart != null)
            {
                var it = cart.Value.Split(',').ToList();

                for (int i = 0; i < it.Count(); i++)
                {
                    if (it[i] != "")
                    {
                        var a = it[i].Split('-').ToList();
                        var product = new ProductDao().ViewDetail(long.Parse(a[0]));
                        var item = new CartItem();
                        item.Product = product;
                        item.Quantity = int.Parse(a[1]);
                        list.Add(item);
                    }

                }
            }
            if (user != null)
            {
                var a = new UserDao().GetById(user.Value);
                var usermodel = a;
                ViewBag.shipName = usermodel.Name;
                ViewBag.mobile = usermodel.Phone;
                ViewBag.address = usermodel.Address;
                ViewBag.email = usermodel.Email;
            }
            return View(list);
        }
        public ActionResult Payment(string shipName, string mobile, string address, string email)
        {
            var order = new Order();
            order.CreatedDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipMobile = mobile;
            order.ShipEmail = email;
            order.ShipName = shipName;
            if(Session[Common.CommonConstants.USER_SESSION] == null)
            {
                order.CustomerID = 0;
            }
            else order.CustomerID = ((UserLogin)Session[Common.CommonConstants.USER_SESSION]).UserID;
            try
            {
                var id = new OrderDao().Insert(order);
                var cart = Request.Cookies[CartCoockies];
                var list = new List<CartItem>();
                var it = cart.Value.Split(',').ToList();//Số sản phẩm có trong cart được cắt bởi dấu ","

                for (int i = 0; i < it.Count(); i++)
                {
                    if (it[i] != "")
                    {
                        var a = it[i].Split('-').ToList();//đối với mỗi sản phẩm ta sẽ cắt chuỗi tại "-" để lấy ra id và số lượng
                        var product = new ProductDao().ViewDetail(long.Parse(a[0]));
                        var item = new CartItem();
                        item.Product = product;
                        item.Quantity = int.Parse(a[1]);
                        list.Add(item);
                    }

OnlineShop/Views/Cart1/Index.cshtml
@model List<OnlineShop.Models.CartItem>

@using PagedList.Mvc

@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section jsFooter {

    <script src="/Assets/Client/js/controllers/cart1Controller.js"></script>
}

<div class="privacy py-sm-5 py-4">
    @if (Model.Count > 0)
    {
        <div class="container py-xl-4 py-lg-2">
            <!-- tittle heading -->
            <h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
                <span>G</span>iỏ hàng
            </h3>
            <!-- //tittle heading -->
            <div class="checkout-right">
                <h4 class="mb-sm-4 mb-3">
                    Tổng:
                    <span id="totalItem">@Model.Count Sản phẩm</span>
                </h4>

                <a href="/san-pham" class="btn btn-success mb-2">Tiếp tục mua</a>
                <a href="#" id="btnUpdateCart" class="btn btn-warning mb-2" style="color:white">Cập nhật giỏ</a>
                <div class="table-responsive">
                    <table class="timetable_sub">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Tên</th>
                                <th>Giá</th>
                                <th>Xóa</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int i = 0; }
                            @foreach (var item in Model)
                            {
                                i++;
                                <tr class="rem1" data-id="@item.Product.ID">
                                    <td class="invert">@i</td>
                                    <td class="invert-image">
                                        <a href="/chi-tiet/@item.Product.MetaTitle-@item.Product.ID">
                                            <img src="@item.Product.Image" alt="@item.Product.MetaTitle" class="img-responsive" style="width:50px; height:50px">
                                        </a>
                                    </td>
                                    <td class="invert">
                                        <div class="quantity">
                                            <div class="quantity-select">
                                                <i class="fa fa-minus quantityDecre"></i>
                                                <span>@item.Quantity</span>
                                                <i class="fa fa-plus quantityIncre"></i>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="invert">@item.Product.Name</td>
                                    <td class="invert">@(item.Product.PromotionPrice.HasValue ? @item.Product.PromotionPrice.Value.ToString("N0") +" Vnđ" : "Liên hệ")</td>
                                    <td class="invert">
                                        <div class="rem">
                                            <div class="close1" data-id="@item.Product.ID"></div>
                                        </div>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                    @*@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))*@
                </div>
            </div>
            <div class="checkout-left">
                <div class="address_form_agile mt-sm-5 mt-4">
                    <h4 class="mb-sm-4 mb-3">Thông tin chi tiết</h4>
                    <div class="creditly-wrapper wthree, w3_agileits_wrapper">
                        <div class="information-wrapper">
                            <div class="first-row">
                                @using (Html.BeginForm("Payment", "Cart1", FormMethod.Post))
                                {
                                    <div class="controls form-group">
                                        <input class="billing-address-name form-control" type="text" name="shipName" placeholder="Họ tên" required="required">
                                    </div>
                                    <div class="w3_agileits_card_number_grids">
                                        <div class="w3_agileits_card_number_grid_left form-group">
                                            <div class="controls">
                                                <input type="text" class="form-control" placeholder="Số điện thoại" name="mobile" required="required">
                                            </div>
                                        </div>
                                        <div class="w3_agileits_card_number_grid_right form-group">
                                            <div class="controls">
                                                <input type="text" class="form-control" placeholder="email" name="email" required="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="controls form-group">
                                        <input type="text" class="form-control" placeholder="Địa chỉ nhận hàng" name="address" required="required">
                                    </div>
                                    <div class="controls form-group">
                                        <select class="option-w3ls">
                                            <option>Phương thức thanh toán</option>
                                            <option>Thanh toán khi nhận hàng</option>
                                            <option>Momo</option>
                                            <option>Paypal</option>
                                        </select>
                                    </div>
                                    @*<div id="btnPayment" class="btn btn-secondary">Đặt hàng</div>*@
                                    <button type="submit" class="btn">Đặt hàng</button>
                                }

                            </div>

                        </div>
                    </div>
                   @* <div class="checkout-right-basket">
                        <a href="/Cart1Controller/Payment">
                            Thanh toán ngay
                            <span class="far fa-hand-point-right"></span>
                        </a>
                    </div>*@
                </div>
            </div>
        </div>
    }
    else
    {
        <p class="text-uppercase ml-5">
            No items
        </p>
    }
</div>